
export interface District {
  id: string;
  bn: string;
  en: string;
  offset: number; // minutes relative to Dhaka
}

export const DISTRICTS: District[] = [
  { id: 'dhaka', bn: 'ঢাকা', en: 'Dhaka', offset: 0 },
  { id: 'gazipur', bn: 'গাজীপুর', en: 'Gazipur', offset: 0 },
  { id: 'narayanganj', bn: 'নারায়ণগঞ্জ', en: 'Narayanganj', offset: 0 },
  { id: 'manikganj', bn: 'মানিকগঞ্জ', en: 'Manikganj', offset: 1 },
  { id: 'munshiganj', bn: 'মুন্সীগঞ্জ', en: 'Munshiganj', offset: 0 },
  { id: 'narsingdi', bn: 'নরসিংদী', en: 'Narsingdi', offset: -1 },
  { id: 'faridpur', bn: 'ফরিদপুর', en: 'Faridpur', offset: 2 },
  { id: 'gopalganj', bn: 'গোপালগঞ্জ', en: 'Gopalganj', offset: 2 },
  { id: 'madaripur', bn: 'মাদারীপুর', en: 'Madaripur', offset: 1 },
  { id: 'rajbari', bn: 'রাজবাড়ী', en: 'Rajbari', offset: 2 },
  { id: 'shariatpur', bn: 'শরীয়তপুর', en: 'Shariatpur', offset: 1 },
  { id: 'kishoreganj', bn: 'কিশোরগঞ্জ', en: 'Kishoreganj', offset: -2 },
  { id: 'tangail', bn: 'টাঙ্গাইল', en: 'Tangail', offset: 1 },
  { id: 'mymensingh', bn: 'ময়মনসিংহ', en: 'Mymensingh', offset: -1 },
  { id: 'jamalpur', bn: 'জামালপুর', en: 'Jamalpur', offset: 1 },
  { id: 'netrokona', bn: 'নেত্রকোণা', en: 'Netrokona', offset: -2 },
  { id: 'sherpur', bn: 'শেরপুর', en: 'Sherpur', offset: 0 },
  { id: 'chattogram', bn: 'চট্টগ্রাম', en: 'Chattogram', offset: -5 },
  { id: 'coxsbazar', bn: 'কক্সবাজার', en: 'Cox\'s Bazar', offset: -6 },
  { id: 'khagrachhari', bn: 'খাগড়াছড়ি', en: 'Khagrachhari', offset: -4 },
  { id: 'rangamati', bn: 'রাঙ্গামাটি', en: 'Rangamati', offset: -4 },
  { id: 'bandarban', bn: 'বান্দরবান', en: 'Bandarban', offset: -5 },
  { id: 'brahmanbaria', bn: 'ব্রাহ্মণবাড়িয়া', en: 'Brahmanbaria', offset: -2 },
  { id: 'chandpur', bn: 'চাঁদপুর', en: 'Chandpur', offset: -1 },
  { id: 'cumilla', bn: 'কুমিল্লা', en: 'Cumilla', offset: -3 },
  { id: 'lakshmipur', bn: 'লক্ষ্মীপুর', en: 'Lakshmipur', offset: -1 },
  { id: 'noakhali', bn: 'নোয়াখালী', en: 'Noakhali', offset: -2 },
  { id: 'feni', bn: 'ফেনী', en: 'Feni', offset: -3 },
  { id: 'sylhet', bn: 'সিলেট', en: 'Sylhet', offset: -6 },
  { id: 'habiganj', bn: 'হবিগঞ্জ', en: 'Habiganj', offset: -4 },
  { id: 'moulvibazar', bn: 'মৌলভীবাজার', en: 'Moulvibazar', offset: -5 },
  { id: 'sunamganj', bn: 'সুনামগঞ্জ', en: 'Sunamganj', offset: -5 },
  { id: 'rajshahi', bn: 'রাজশাহী', en: 'Rajshahi', offset: 6 },
  { id: 'bogura', bn: 'বগুড়া', en: 'Bogura', offset: 3 },
  { id: 'joypurhat', bn: 'জয়পুরহাট', en: 'Joypurhat', offset: 4 },
  { id: 'naogaon', bn: 'নওগাঁ', en: 'Naogaon', offset: 5 },
  { id: 'natore', bn: 'নাটোর', en: 'Natore', offset: 5 },
  { id: 'chapainawabganj', bn: 'চাঁপাইনবাবগঞ্জ', en: 'Chapainawabganj', offset: 7 },
  { id: 'pabna', bn: 'পাবনা', en: 'Pabna', offset: 4 },
  { id: 'sirajganj', bn: 'সিরাজগঞ্জ', en: 'Sirajganj', offset: 2 },
  { id: 'rangpur', bn: 'রংপুর', en: 'Rangpur', offset: 3 },
  { id: 'dinajpur', bn: 'দিনাজপুর', en: 'Dinajpur', offset: 5 },
  { id: 'gaibandha', bn: 'গাইবান্ধা', en: 'Gaibandha', offset: 2 },
  { id: 'kurigram', bn: 'কুড়িগ্রাম', en: 'Kurigram', offset: 1 },
  { id: 'lalmonirhat', bn: 'লালমনিরহাট', en: 'Lalmonirhat', offset: 2 },
  { id: 'nilphamari', bn: 'নীলফামারী', en: 'Nilphamari', offset: 4 },
  { id: 'panchagarh', bn: 'পঞ্চগড়', en: 'Panchagarh', offset: 6 },
  { id: 'thakurgaon', bn: 'ঠাকুরগাঁও', en: 'Thakurgaon', offset: 6 },
  { id: 'khulna', bn: 'খুলনা', en: 'Khulna', offset: 4 },
  { id: 'bagerhat', bn: 'বাগেরহাট', en: 'Bagerhat', offset: 3 },
  { id: 'chuadanga', bn: 'চুয়াডাঙ্গা', en: 'Chuadanga', offset: 6 },
  { id: 'jessore', bn: 'যশোর', en: 'Jashore', offset: 5 },
  { id: 'jhenaidah', bn: 'ঝিনাইদহ', en: 'Jhenaidah', offset: 5 },
  { id: 'kushtia', bn: 'কুষ্টিয়া', en: 'Kushtia', offset: 5 },
  { id: 'magura', bn: 'মাগুরা', en: 'Magura', offset: 4 },
  { id: 'meherpur', bn: 'মেহেরপুর', en: 'Meherpur', offset: 6 },
  { id: 'narail', bn: 'নড়াইল', en: 'Narail', offset: 4 },
  { id: 'satkhira', bn: 'সাতক্ষীরা', en: 'Satkhira', offset: 6 },
  { id: 'barishal', bn: 'বরিশাল', en: 'Barishal', offset: 2 },
  { id: 'barguna', bn: 'বরগুনা', en: 'Barguna', offset: 2 },
  { id: 'bhola', bn: 'ভোলা', en: 'Bhola', offset: 0 },
  { id: 'jhalokati', bn: 'ঝালকাঠি', en: 'Jhalokathi', offset: 2 },
  { id: 'patuakhali', bn: 'পটুয়াখালী', en: 'Patuakhali', offset: 1 },
  { id: 'pirojpur', bn: 'পিরোজপুর', en: 'Pirojpur', offset: 3 }
].sort((a, b) => a.en.localeCompare(b.en));
